version: '3'

services:
  db:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
     build: .
     container_name: questions-collector
     restart: always
     volumes:
       - .:/usr/src/questions
     ports:
       - "80:80"
     depends_on:
       - db

volumes:
  postgres_data:
